# Generated by Django 4.2.7 on 2025-08-03 12:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "make",
                    models.CharField(
                        help_text="Vehicle manufacturer (e.g., Toyota, Honda)",
                        max_length=100,
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        help_text="Vehicle model (e.g., Camry, Civic)", max_length=100
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        help_text="Manufacturing year",
                        validators=[
                            django.core.validators.MinValueValidator(
                                1900, message="Year must be 1900 or later"
                            ),
                            django.core.validators.MaxValueValidator(
                                2030, message="Year cannot be in the future"
                            ),
                        ],
                    ),
                ),
                (
                    "license_plate",
                    models.CharField(
                        help_text="Vehicle license plate number",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("sedan", "Sedan"),
                            ("suv", "SUV"),
                            ("hatchback", "Hatchback"),
                            ("convertible", "Convertible"),
                            ("truck", "Truck"),
                            ("van", "Van"),
                            ("luxury", "Luxury"),
                            ("economy", "Economy"),
                        ],
                        default="sedan",
                        help_text="Type of vehicle",
                        max_length=20,
                    ),
                ),
                (
                    "fuel_type",
                    models.CharField(
                        choices=[
                            ("petrol", "Petrol"),
                            ("diesel", "Diesel"),
                            ("electric", "Electric"),
                            ("hybrid", "Hybrid"),
                            ("cng", "CNG"),
                        ],
                        default="petrol",
                        help_text="Type of fuel used",
                        max_length=20,
                    ),
                ),
                (
                    "transmission",
                    models.CharField(
                        choices=[("manual", "Manual"), ("automatic", "Automatic")],
                        default="automatic",
                        help_text="Transmission type",
                        max_length=20,
                    ),
                ),
                (
                    "engine_size",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Engine size in liters",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "mileage",
                    models.PositiveIntegerField(
                        default=0, help_text="Current mileage in kilometers"
                    ),
                ),
                (
                    "daily_rate",
                    models.DecimalField(
                        decimal_places=2, help_text="Daily rental rate", max_digits=10
                    ),
                ),
                (
                    "weekly_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Weekly rental rate (optional)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "monthly_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Monthly rental rate (optional)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("rented", "Rented"),
                            ("maintenance", "Under Maintenance"),
                            ("out_of_service", "Out of Service"),
                        ],
                        default="available",
                        help_text="Current status of the vehicle",
                        max_length=20,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True, help_text="Vehicle color", max_length=50, null=True
                    ),
                ),
                (
                    "seats",
                    models.PositiveSmallIntegerField(
                        default=5, help_text="Number of seats"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Additional description of the vehicle",
                        null=True,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Vehicle image",
                        null=True,
                        upload_to="vehicles/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="User who owns/manages this vehicle",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Vehicle",
                "verbose_name_plural": "Vehicles",
                "db_table": "vehicles",
                "ordering": ["-created_at"],
            },
        ),
    ]
